---
hero_image: images/secure-messages.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Secure Messages 
description: Make your own encryption program, to send and receive secure messages.
original_url: https://codeclubprojects.org/en-GB/python/secure-messages
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
landing: true
steps:
  - title: Take a single character
  - title: Encrypt the character
    completion:
      - engaged
  - title: Encrypt the character
  - title: Wrap around
  - title: "Print the letter at the new position."
  - title: Let the user enter their own key
  - title: Encrypt a full message
  - title: Print the new message on one line
    completion:
      - internal
  - title: Handle special characters
    completion:
      - external
